#!/usr/bin/python3
"""same class or inherit from"""


def is_kind_of_class(obj, a_class):
    """
    function that returns True if obj is
    instance of inherited class
    """
    return (isinstance(obj, a_class))
